### ISSUE TITLE
Interactive code examples

### ISSUE THREAD

**Issue by nalgeon** [chdb-io/chdb-docs#2]
Hi folks! I'm writing about the interactive code examples in the chDB docs (we discussed this with @auxten on [twitter](https://twitter.com/ohmypy/status/1734190186043703643) and with @lmangani on [HN](https://news.ycombinator.com/item?id=38601280)).

Here is what I propose:

1. doc.chdb.io can use the codapi cloud version (codapi.org) for now. You can always switch to the self-hosted codapi version if you wish so (or when chDB gains so much popularity that the docs traffic becomes unbearable for the codapi cloud).

2. As far as I can see, chDB docs are based on docsify.js, which is a nice little tool. I think I can prepare a PR for interactive Python code examples using it.

3. Once everyone is happy with the Python docs, we can repeat this for other languages.

What do you think?

**Comment by lmangani** [comment]
@nalgeon thanks for opening this thread and for the amazing example you've built already! 
I would be thrilled to see this integration happen for the chdb docs and make this a long term integration. 
I think you proposed already an excellent plan:

1. We can list codapi as a chdb sponsor/supporter to promote it back in return until we make it independent
2.  Docsify should be quite flexible and I'l really curious to see how its done
3. 🥳 And this is where the community fun begins!

**Comment by nalgeon** [comment]
Okay, the Python examples are out, so now I'll work on Go, Rust and others. It will probably take some time because I have to prepare the sandboxes (currently there is only a Python one), but sooner or later I'll be back with PRs :)

On a related note, I've noticed that there is a two-level tab hierarchy in the docs (top level is the language switcher, second level is the example switcher). In my experience, it is more convenient for the reader to scroll up/down to view examples than to switch tabs. So I think it's better to change the example tabs to a linear flow.

The top-level (language) sections may also be better as a separate pages.

That's beyond the scope of this issue, of course. Just a thought.

**Comment by lmangani** [comment]
@nalgeon thanks and please count on me for any task/collaboration required

>  In my experience, it is more convenient for the reader to scroll up/down to view examples than to switch tabs. So I think it's better to change the example tabs to a linear flow.

I fully agree and I actually like your demo structure a lot better. Perhaps we should just port it as it was into the docs now that we have interactivity?

**Comment by nalgeon** [comment]
I thought I didn't change the structure 🤔 Or do you mean the [blog post](https://antonz.org/trying-chdb/)?

**Comment by lmangani** [comment]
Sorry for the confusion what I meant is I like [your examples](https://antonz.org/trying-chdb/) and the vertical ordering so much better than our tabbed examples (except for the installation parts) as well (honestly i would port to docs it as-is)

**Comment by nalgeon** [comment]
Oh, okay, sure. I'll prepare the PR with these changes then.

**Comment by lmangani** [comment]
Closing as completed!
